# Generated by Django 5.1.6 on 2025-02-28 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0002_alter_profile_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='amount',
            field=models.IntegerField(null=True, verbose_name='amount'),
        ),
        migrations.AddField(
            model_name='entry',
            name='date',
            field=models.DateField(null=True, verbose_name='date'),
        ),
    ]
