# Generated by Django 5.1.6 on 2025-02-28 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0003_entry_amount_entry_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='budget',
            field=models.IntegerField(null=True),
        ),
    ]
