# Generated by Django 5.1.6 on 2025-03-01 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0004_profile_budget'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='expense',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='month',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='savings',
            field=models.IntegerField(null=True),
        ),
    ]
